# /wrangler.toml
name = "doughmonster-worker"
main = "src/worker.ts"            # we'll create this file next
compatibility_date = "2024-11-01"
logpush = true

[observability]
enabled = true

# Public, non-secret defaults (safe to commit)
[vars]
TOAST_API_BASE = "https://ws-api.toasttab.com"
TOAST_AUTH_URL = "https://ws-api.toasttab.com/authentication/v1/authentication/login"
