# /wrangler.toml
name = "doughmonster-worker"
main = "src/worker.ts"
compatibility_date = "2024-11-01"
logpush = true

[observability]
enabled = true

[vars]
TOAST_API_BASE = "https://ws-api.toasttab.com"
TOAST_AUTH_URL = "https://ws-api.toasttab.com/authentication/v1/authentication/login"

# KV namespace for caching Toast tokens
[[kv_namespaces]]
binding = "TOKEN_KV"
id = "REPLACE_WITH_PROD_KV_ID"
